# Generated by Django 5.2.8 on 2025-11-10 15:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Lesson content with rich text formatting (optional)', null=True),
        ),
    ]
