# Generated by Django 5.2.8 on 2025-11-10 15:41

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lesson_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Goşmaça faýl', 'verbose_name_plural': 'Goşmaça faýllar'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order', '-date_created'], 'verbose_name': 'Sapak', 'verbose_name_plural': 'Sapaklar'},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='description',
            field=models.TextField(blank=True, help_text='Goşmaça düşündiriş (hökmany däl)', null=True, verbose_name='Düşündiriş'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='lesson_attachments/%Y/%m/%d/', verbose_name='Faýl'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_size',
            field=models.IntegerField(blank=True, help_text='Faýlyň ululygy baýtda', null=True, verbose_name='Faýl ululygy'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='lessons.lesson', verbose_name='Sapak'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='title',
            field=models.CharField(help_text='Goşmaça faýlyň ady', max_length=200, verbose_name='Ady'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ýüklenen senesi'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Baý tekst formatlaşdyrma bilen sapagyň mazmuny (hökmany däl)', null=True, verbose_name='Mazmun'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Döredilen senesi'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Täzelenen senesi'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, help_text='Gysga düşündiriş', max_length=500, null=True, verbose_name='Düşündiriş'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Talyplara görkezilsin', verbose_name='Çap edildi'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(default=0, help_text='Görkeziş tertibi (pes sanlar öň görkeziler)', verbose_name='Tertip belgisi'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Sapagyň ady'),
        ),
    ]
